<?php

	$reporte_ots = array('CLIENTE','PRODUCTO','OT','REFERENCIA OT','FECHA CREACIÓN OT','HORA CREACIÓN OT','# TAREA','TIPO TAREA','FECHA TAREA','REFERENCIA','AREA','RESPONSABLE','ASIGNADO','ESTADO TAREA','FECHA PROMETIDA','HORA PROMETIDA');
	$estados_pptos = array('CLIENTE','PRODUCTO','OT','REFERENCIA OT','FECHA CREACIÓN OT','HORA CREACIÓN OT','# PPTO INTERNO','# PPTO EXTERNO','REFERENCIA PPTO','ESTADO PPTO');
	$items_pendiente_ordenacion = array('CLIENTE','PRODUCTO','OT','REFERENCIA OT','FECHA CREACIÓN OT','HORA CREACIÓN OT','# PPTO INTERNO','# PPTO EXTERNO','REFERENCIA PPTO','ESTADO PPTO',
	'PROVEEDOR','ITEM','DIAS','CANTIDAD','$ VALOR UNITARIO</BR>(INTERNO)','% IVA','% VOLUMEN','TOTAL');
	
	$facturas_pendientes_por_llegar = array('CLIENTE','PRODUCTO','OT','REFERENCIA OT','FECHA CREACIÓN OT','HORA CREACIÓN OT','# PPTO INTERNO','# PPTO EXTERNO','REFERENCIA PPTO','ESTADO PPTO',
	'PROVEEDOR','# OC', 'FECHA RADICACIÓN OC','$ SUBTOTAL OC', '$ IVA OC','TOTAL OC');
	
	$facturacion_proveedor = array('PROVEEDOR','# ORDEN COMPRA','FECHA RADICACIÓN OC','FACTURA','$ SUBTOTAL','$ IVA','TOTAL','ESTADO','FECHA RADICACIÓN FACT.');
?>